apiVersion: v1
kind: Service
metadata:
  name: watson-nlp-runtime-service
spec:
  type: LoadBalancer
  selector:
    app: watson-nlp-runtime
  ports:
  - port: 8080
    name: http-rest-svc
    protocol: TCP
    targetPort: 8080
  - port: 8085
    name: http-grpc-svc
    protocol: TCP
    targetPort: 8085
