apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-app
spec:
  selector:
    matchLabels:
      app: dash-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dash-app
    spec:
      containers:
      - name: dash-app
        image: image-registry.openshift-image-registry.svc:5000/openshift/dash-app-grpc:latest
        env:
          - name: EMOTION_CLASSIFICATION_STOCK_MODEL
            valueFrom:
              configMapKeyRef:
                key: EMOTION_CLASSIFICATION_STOCK_MODEL
                name: dahsapp-config
          - name: GRPC_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: GRPC_SERVER_URL
                name: dahsapp-config
          - name: SENTIMENT_DOCUMENT_CNN_WORKFLOW_MODEL
            valueFrom:
              configMapKeyRef:
                key: SENTIMENT_DOCUMENT_CNN_WORKFLOW_MODEL
                name: dahsapp-config
          - name: SYNTAX_IZUMO_EN_STOCK_MODEL
            valueFrom:
              configMapKeyRef:
                key: SYNTAX_IZUMO_EN_STOCK_MODEL
                name: dahsapp-config
        ports:
        - containerPort: 8050